# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true
  
  # Vagrant Client Name Service Broken
  # http://askubuntu.com/questions/238040/how-do-i-fix-name-service-for-vagrant-client
  # https://bugs.launchpad.net/ubuntu/+source/virtualbox/+bug/1048783
  #
  # This is a known issue in Ubuntu 12.10 where name resolution is broken
  # the following modifications fix the issue
  config.vm.provider :virtualbox do |v|
    # This setting makes it so that network access from inside the vagrant guest
    # is able to resolve DNS using the hosts VPN connection.
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
end